export const AUTHENTICATE_USER = 'AUTHENTICATE_USER';
export const AUTHENTICATE_USER_SOCIAL = 'AUTHENTICATE_USER_SOCIAL';
export const SIGNUP_SOCIAL = 'SIGNUP_SOCIAL';
export const SIGNUP_DIRECT = 'SIGNUP_DIRECT';
